import type { Metadata } from "next";

import "./globals.css";

import NavBarJs from "@/app/ui/components/Navbar/NavBarJs";
import ParticleBackground from "@/app/ui/components/ParticleBackground";
import { instrumentSerif, poppins } from "./font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} ${instrumentSerif.className} antialiased`}
      >
        <ParticleBackground />
        <NavBarJs />
        {children}
      </body>
    </html>
  );
}
