import type { Metadata } from "next";

import "./globals.css";

import NavBarJs from "../components/Navbar/NavBarJs";
import ParticleBackground from "../components/ParticleBackground";
import { poppins } from "./font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`w-[100vw] bg-gradient-to-tr from-black via-gray-900 to-black  overflow-x-hidden ${poppins.className} antialiased`}
      >
        <ParticleBackground />
        <NavBarJs />
        {children}
      </body>
    </html>
  );
}
